name: Rustdoc link check
description: "Discover broken Rust documentation links."
inputs:
    private:
        description: "Check links in documentation of private items too"
        required: false
        default: true
    working-directory:
        description: "The working directory to check for broken links"
        required: false,
        default: "./"
runs:
    using: "node16"
    main: "index.js"
